services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000 --verbosity 3
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - .env  # This will ensure the .env file is loaded
    environment:
      - PYTHONDONTWRITEBYTECODE=1
      - PYTHONUNBUFFERED=1
    depends_on:
      - db
      - redis

  db:
    image: postgres:16.2
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB_HOST=${POSTGRES_HOST}

  redis:
    image: redis:latest
    ports:
      - "6379:6379"

volumes:
  postgres_data:
