services:
  web:
    build: .
    command:  bash -c "gunicorn annonymous_chat.wsgi:application --bind 0.0.0.0:8001 --reload --timeout 120 --workers 3 --log-file - --log-level debug"
    restart: always
    volumes:
      - .:/app
      - static_files:/app/annonymous_chat/staticfiles/
      - media_files:/app/annonymous_chat/media/
    env_file:
      - .env  # This ensures the .env file is loaded
    environment:
      - PYTHONDONTWRITEBYTECODE=1
      - PYTHONUNBUFFERED=1
    ports:
      - "8001:8001"  # Corrected port mapping to match internal gunicorn port
    depends_on:
      - db

  db:
    image: postgres:16.2
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}

volumes:
  postgres_data:
  static_files:  # Corrected volume name for static files
  media_files:
