# Generated by Django 4.2.3 on 2024-12-18 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatroom',
            name='max_participants',
            field=models.IntegerField(default=2),
        ),
        migrations.AlterField(
            model_name='chatroom',
            name='is_private',
            field=models.BooleanField(default=True),
        ),
    ]
