# Generated by Django 4.2.3 on 2024-12-18 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_chatroom_max_participants_alter_chatroom_is_private'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatroom',
            name='is_private',
        ),
    ]
