# Generated by Django 4.2.3 on 2024-12-18 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_remove_chatroom_is_private'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatmessage',
            name='receiver_id',
        ),
    ]
