# Generated by Django 4.2.3 on 2024-12-18 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_remove_chatmessage_receiver_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='sender_role',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
