# Generated by Django 4.2.3 on 2024-12-18 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_chatmessage_sender_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmessage',
            name='sender_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='chatroom',
            name='room_code',
            field=models.CharField(blank=True, max_length=200, null=True, unique=True),
        ),
    ]
