# Generated by Django 4.2.3 on 2024-12-20 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_alter_chatmessage_sender_id_alter_chatroom_room_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='status',
            field=models.CharField(choices=[('delivered', 'Delivered'), ('read', 'Read'), ('deleted', 'Deleted')], default='delivered', max_length=255),
        ),
    ]
