# Generated by Django 4.2.3 on 2024-12-24 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0007_chatmessage_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatroom',
            name='expiration_duration',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='chatroom',
            name='expiration_duration_unit',
            field=models.CharField(choices=[('minutes', 'Minutes'), ('hours', 'Hours'), ('days', 'Days')], default='minutes', max_length=20),
        ),
        migrations.AddField(
            model_name='chatroom',
            name='expiration_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='chatroom',
            name='max_participants',
            field=models.IntegerField(default=10),
        ),
    ]
