# Generated by Django 4.2.3 on 2024-12-26 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0008_chatroom_expiration_duration_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatroom',
            name='expiration_duration_unit',
            field=models.CharField(choices=[('m', 'Minutes'), ('h', 'Hours'), ('d', 'Days')], default='minutes', max_length=20),
        ),
    ]
