# Generated by Django 4.2.3 on 2025-01-10 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0011_alter_chatroom_expiration_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatroom',
            name='admin_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
